<?php

namespace App\Services;

use App\Models\Template;
use App\Models\TemplatePage;
use App\Models\TemplateSection;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class TemplateFileGenerator
{
    protected string $baseDirectory;

    public function __construct()
    {
        $this->baseDirectory = public_path('template_directory');

        // Ensure base directory exists
        if (!File::exists($this->baseDirectory)) {
            File::makeDirectory($this->baseDirectory, 0755, true);
        }
    }

    /**
     * Generate or regenerate all files for a template
     */
    public function generateTemplateFiles(Template $template): string
    {
        // Ensure template has a slug
        if (!$template->template_slug) {
            $template->template_slug = $this->generateSlug($template);
            $template->save();
        }

        $templatePath = $this->getTemplatePath($template);

        // Create template directory
        if (!File::exists($templatePath)) {
            File::makeDirectory($templatePath, 0755, true);
        }

        // Create assets directories
        $assetsPath = $templatePath . '/assets';
        File::ensureDirectoryExists($assetsPath . '/css', 0755, true);
        File::ensureDirectoryExists($assetsPath . '/js', 0755, true);
        File::ensureDirectoryExists($assetsPath . '/images', 0755, true);

        // Copy images from template gallery
        $this->copyTemplateImages($template, $assetsPath . '/images');

        // Generate CSS file
        $this->generateStylesheet($template, $assetsPath . '/css/style.css');

        // Generate HTML files for each page
        foreach ($template->pages as $page) {
            $this->generatePageHTML($template, $page, $templatePath);
        }

        return $templatePath;
    }

    /**
     * Generate a slug for the template
     */
    protected function generateSlug(Template $template): string
    {
        if ($template->is_active) {
            // Published template: use clean name-based slug
            $baseSlug = Str::slug($template->name);
            $slug = $baseSlug;
            $counter = 1;

            // Ensure uniqueness
            while (Template::where('template_slug', $slug)->where('id', '!=', $template->id)->exists()) {
                $slug = $baseSlug . '-' . $counter;
                $counter++;
            }

            return $slug;
        } else {
            // Unpublished template: use random string
            return Str::random(10);
        }
    }

    /**
     * Get the full path to template directory
     */
    public function getTemplatePath(Template $template): string
    {
        return $this->baseDirectory . '/' . $template->template_slug;
    }

    /**
     * Get the URL to template directory
     */
    public function getTemplateUrl(Template $template): string
    {
        return url('template_directory/' . $template->template_slug);
    }

    /**
     * Copy template images to assets folder
     */
    protected function copyTemplateImages(Template $template, string $targetPath): void
    {
        if (!$template->images || !is_array($template->images)) {
            return;
        }

        File::ensureDirectoryExists($targetPath, 0755, true);

        foreach ($template->images as $image) {
            $sourcePath = public_path($image['path'] ?? '');
            if (File::exists($sourcePath)) {
                $filename = basename($sourcePath);
                File::copy($sourcePath, $targetPath . '/' . $filename);
            }
        }
    }

    /**
     * Generate stylesheet (CSS) file
     */
    protected function generateStylesheet(Template $template, string $outputPath): void
    {
        $css = $this->buildStylesheet($template);
        File::put($outputPath, $css);
    }

    /**
     * Build complete stylesheet content
     */
    protected function buildStylesheet(Template $template): string
    {
        $css = "/*\n * Generated Stylesheet for {$template->name}\n * Generated by Pagevoo Template Builder\n */\n\n";

        // Base Reset and Box Sizing
        $css .= "/* Base Reset */\n\n";
        $css .= "*, *::after, *::before {\n";
        $css .= "  box-sizing: border-box;\n";
        $css .= "  margin: 0;\n";
        $css .= "  padding: 0;\n";
        $css .= "}\n\n";

        $css .= "body {\n";
        $css .= "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n";
        $css .= "  line-height: 1.6;\n";
        $css .= "}\n\n";

        // Navigation Base Styles
        $css .= "/* Navigation Base Styles */\n\n";
        $css .= "nav[class*=\"navbar-\"], header[class*=\"header-\"] {\n";
        $css .= "  display: flex;\n";
        $css .= "  align-items: center;\n";
        $css .= "  justify-content: space-between;\n";
        $css .= "  padding: 1rem 2rem;\n";
        $css .= "}\n\n";

        $css .= ".nav-links {\n";
        $css .= "  display: flex;\n";
        $css .= "  gap: 1.5rem;\n";
        $css .= "  align-items: center;\n";
        $css .= "}\n\n";

        $css .= ".logo {\n";
        $css .= "  font-size: 1.5rem;\n";
        $css .= "  font-weight: bold;\n";
        $css .= "}\n\n";

        // Responsive Grid System
        $css .= "/* Responsive Grid System */\n\n";
        $css .= "[class*=\"col-\"] {\n";
        $css .= "  float: left;\n";
        $css .= "  padding: 20px;\n";
        $css .= "  width: 100%;\n";
        $css .= "}\n\n";

        $css .= ".row::after {\n";
        $css .= "  content: \"\";\n";
        $css .= "  clear: both;\n";
        $css .= "  display: table;\n";
        $css .= "}\n\n";

        // Site-wide CSS
        if ($template->custom_css) {
            $css .= "/* Site-Wide Styles */\n\n";
            $css .= $template->custom_css . "\n\n";
        }

        // Page-specific and section CSS
        foreach ($template->pages as $page) {
            if ($page->page_css) {
                $css .= "/* Page: {$page->name} */\n\n";
                $css .= $page->page_css . "\n\n";
            }

            foreach ($page->sections as $section) {
                $this->addSectionCSS($css, $section);
            }
        }

        // Responsive breakpoints
        $css .= "/* Responsive Breakpoints */\n\n";
        $css .= "@media (min-width: 768px) {\n";
        for ($i = 1; $i <= 12; $i++) {
            $width = round(($i / 12) * 100, 2);
            $css .= "  .col-{$i} { width: {$width}%; }\n";
        }
        $css .= "}\n\n";

        $css .= "@media (min-width: 1025px) {\n";
        for ($i = 1; $i <= 12; $i++) {
            $width = round(($i / 12) * 100, 2);
            $css .= "  .col-{$i} { width: {$width}%; }\n";
        }
        $css .= "}\n";

        return $css;
    }

    /**
     * Add section-specific CSS
     */
    protected function addSectionCSS(string &$css, TemplateSection $section): void
    {
        $sectionId = $section->section_id ?? "section-{$section->id}";
        $content = $section->content ?? [];

        // Section CSS
        if (isset($content['section_css'])) {
            $css .= "/* Section: {$section->section_name} */\n";
            $css .= "#{$sectionId} {\n";
            $css .= "  " . trim($content['section_css']) . "\n";
            $css .= "}\n\n";
        }

        // Navigation/Header styling
        if (str_starts_with($section->type, 'navbar-') || str_starts_with($section->type, 'header-')) {
            $this->addNavigationCSS($css, $section, $sectionId, $content);
        }
    }

    /**
     * Add navigation-specific CSS
     */
    protected function addNavigationCSS(string &$css, TemplateSection $section, string $sectionId, array $content): void
    {
        // Container Style
        if (isset($content['containerStyle'])) {
            $cs = $content['containerStyle'];
            $css .= "/* {$section->section_name} - Container */\n";
            $css .= "#{$sectionId} {\n";
            if (isset($cs['background'])) $css .= "  background: {$cs['background']};\n";
            if (isset($cs['paddingTop'])) $css .= "  padding-top: {$cs['paddingTop']}px;\n";
            if (isset($cs['paddingRight'])) $css .= "  padding-right: {$cs['paddingRight']}px;\n";
            if (isset($cs['paddingBottom'])) $css .= "  padding-bottom: {$cs['paddingBottom']}px;\n";
            if (isset($cs['paddingLeft'])) $css .= "  padding-left: {$cs['paddingLeft']}px;\n";
            if (isset($cs['borderWidth'])) $css .= "  border-width: {$cs['borderWidth']}px;\n";
            if (isset($cs['borderStyle']) && $cs['borderStyle'] !== 'none') $css .= "  border-style: {$cs['borderStyle']};\n";
            if (isset($cs['borderColor'])) $css .= "  border-color: {$cs['borderColor']};\n";
            if (isset($cs['borderRadius'])) $css .= "  border-radius: {$cs['borderRadius']}px;\n";
            $css .= "}\n\n";
        }

        // Link Styling
        if (isset($content['linkStyling'])) {
            $ls = $content['linkStyling'];
            $css .= "/* {$section->section_name} - Links */\n";
            $css .= "#{$sectionId} a {\n";
            if (isset($ls['textColor'])) $css .= "  color: {$ls['textColor']};\n";
            if (isset($ls['bgColor'])) $css .= "  background-color: {$ls['bgColor']};\n";
            if (isset($ls['fontSize'])) $css .= "  font-size: {$ls['fontSize']}px;\n";
            $css .= "  text-decoration: none;\n";
            $css .= "}\n\n";

            $css .= "#{$sectionId} a:hover {\n";
            if (isset($ls['textColorHover'])) $css .= "  color: {$ls['textColorHover']};\n";
            if (isset($ls['bgColorHover'])) $css .= "  background-color: {$ls['bgColorHover']};\n";
            $css .= "}\n\n";
        }
    }

    /**
     * Generate HTML file for a page
     */
    protected function generatePageHTML(Template $template, TemplatePage $page, string $templatePath): void
    {
        $filename = $page->is_homepage ? 'index.html' : $page->slug . '.html';
        $html = $this->buildPageHTML($template, $page);
        File::put($templatePath . '/' . $filename, $html);
    }

    /**
     * Build complete HTML content for a page
     */
    protected function buildPageHTML(Template $template, TemplatePage $page): string
    {
        $html = "<!DOCTYPE html>\n";
        $html .= "<html lang=\"en\">\n";
        $html .= "<head>\n";
        $html .= "  <meta charset=\"UTF-8\">\n";
        $html .= "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
        $html .= "  <title>{$page->name}</title>\n";
        if ($page->meta_description) {
            $html .= "  <meta name=\"description\" content=\"{$page->meta_description}\">\n";
        }
        $html .= "  <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n";
        $html .= "</head>\n";
        $html .= "<body>\n\n";

        // Generate sections
        foreach ($page->sections()->orderBy('order')->get() as $section) {
            $html .= $this->buildSectionHTML($section);
            $html .= "\n\n";
        }

        $html .= "</body>\n";
        $html .= "</html>";

        return $html;
    }

    /**
     * Build HTML for a single section
     */
    protected function buildSectionHTML(TemplateSection $section): string
    {
        $sectionId = $section->section_id ?? "section-{$section->id}";
        $content = $section->content ?? [];

        // Navigation/Header sections
        if (str_starts_with($section->type, 'navbar-') || str_starts_with($section->type, 'header-')) {
            return $this->buildNavigationHTML($section, $sectionId, $content);
        }

        // Grid sections
        if (str_starts_with($section->type, 'grid-')) {
            return $this->buildGridHTML($section, $sectionId, $content);
        }

        // Default section
        return "<section id=\"{$sectionId}\" class=\"{$section->type}\">\n  <!-- {$section->type} -->\n</section>";
    }

    /**
     * Build navigation/header HTML
     */
    protected function buildNavigationHTML(TemplateSection $section, string $sectionId, array $content): string
    {
        $tag = str_starts_with($section->type, 'navbar-') ? 'nav' : 'header';
        $html = "<{$tag} id=\"{$sectionId}\" class=\"{$section->type}\">\n";
        $html .= "  <div class=\"logo\">" . ($content['logo'] ?? 'Logo') . "</div>\n";

        $links = $content['links'] ?? [];
        if (count($links) > 0) {
            $html .= "  <div class=\"nav-links\">\n";
            foreach ($links as $link) {
                $label = is_array($link) ? ($link['label'] ?? 'Link') : $link;
                $href = is_array($link) && isset($link['url']) ? $link['url'] : '#';
                $html .= "    <a href=\"{$href}\">{$label}</a>\n";
            }
            $html .= "  </div>\n";
        }

        $html .= "</{$tag}>";
        return $html;
    }

    /**
     * Build grid section HTML
     */
    protected function buildGridHTML(TemplateSection $section, string $sectionId, array $content): string
    {
        $html = "<section id=\"{$sectionId}\">\n";
        $html .= "  <div class=\"row\">\n";

        $columns = $content['columns'] ?? [];
        foreach ($columns as $col) {
            $colWidth = $col['colWidth'] ?? 12;
            $colContent = $col['content'] ?? '';
            $html .= "    <div class=\"col-{$colWidth}\">\n";
            $html .= "      {$colContent}\n";
            $html .= "    </div>\n";
        }

        $html .= "  </div>\n";
        $html .= "</section>";
        return $html;
    }

    /**
     * Delete template directory
     */
    public function deleteTemplateFiles(Template $template): bool
    {
        if (!$template->template_slug) {
            return false;
        }

        $templatePath = $this->getTemplatePath($template);

        if (File::exists($templatePath)) {
            File::deleteDirectory($templatePath);
            return true;
        }

        return false;
    }

    /**
     * Regenerate slug when template is published/unpublished
     */
    public function updateSlugOnPublish(Template $template, bool $isNowPublished): void
    {
        $oldPath = $this->getTemplatePath($template);

        // Generate new slug based on published status
        $template->template_slug = $this->generateSlug($template);
        $template->save();

        $newPath = $this->getTemplatePath($template);

        // Move directory if it exists
        if (File::exists($oldPath) && $oldPath !== $newPath) {
            File::move($oldPath, $newPath);
        } else {
            // Generate fresh files
            $this->generateTemplateFiles($template);
        }
    }
}
